# Generated by Django 3.2.5 on 2021-07-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210714_1328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
