# Generated by Django 3.2.5 on 2021-07-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210714_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user1',
            old_name='email',
            new_name='approch',
        ),
        migrations.RenameField(
            model_name='user1',
            old_name='name',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='user1',
            old_name='password',
            new_name='lead',
        ),
    ]
